-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 00:27:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `apartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartment` ;

CREATE TABLE IF NOT EXISTS `apartment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postCode` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number_of_house` VARCHAR(45) NULL DEFAULT NULL,
  `number_of_apartment` VARCHAR(45) NULL DEFAULT NULL,
  `inactive` BIT(1) NULL DEFAULT NULL,
  `Apartmentcol` VARCHAR(45) NULL DEFAULT NULL,
  `owner_id` INT NOT NULL,
  `community_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_apartment_owner1_idx` ON `apartment` (`owner_id` ASC) VISIBLE;

CREATE INDEX `fk_apartment_community1_idx` ON `apartment` (`community_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `community`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community` ;

CREATE TABLE IF NOT EXISTS `community` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `postCode` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number_of_house` VARCHAR(45) NULL DEFAULT NULL,
  `number_of_apartment` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `nip` VARCHAR(45) NULL DEFAULT NULL,
  `inactive` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `community_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community_account` ;

CREATE TABLE IF NOT EXISTS `community_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(45) NULL DEFAULT NULL,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  `inactive` BIT(1) NULL DEFAULT NULL,
  `community_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_community_account_community_idx` ON `community_account` (`community_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `estate_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate_manager` ;

CREATE TABLE IF NOT EXISTS `estate_manager` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `post_code` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number_of_house` VARCHAR(45) NULL DEFAULT NULL,
  `number_of_apartment` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `nip` VARCHAR(45) NULL DEFAULT NULL,
  `logo` BLOB NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;

CREATE TABLE IF NOT EXISTS `invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL,
  `invoice_date` DATE NULL,
  `description` VARCHAR(45) NULL,
  `amount` DECIMAL(8) NULL,
  `date_of_ payment` DATE NULL,
  `owner_id` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_invoice_owner1_idx` ON `invoice` (`owner_id` ASC) VISIBLE;

CREATE INDEX `fk_invoice_apartment1_idx` ON `invoice` (`apartment_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `owner` ;

CREATE TABLE IF NOT EXISTS `owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fitst_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `post_code` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `number_of_house` VARCHAR(45) NULL,
  `number_of_apartments` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `owner_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_user_owner1_idx` ON `user` (`owner_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
